---
driver:
  name: vagrant
  # See: https://github.com/hw-cookbooks/postgresql/issues/212
  require_chef_omnibus: 11.16.2
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-14.04
  driver_config:
    box: chef/ubuntu-14.04
  run_list:
  - recipe[test-helper::default]
  - recipe[apt]
  - recipe[textsecure::default]

default_attributes: &DEFAULT_ATTRIBUTES
  build-essential:
    compile_time: true
  postgresql:
    config:
      ssl: false # Docker-specific fix
    password:
      postgres: whisper
  pushserver: &PUSHSERVER_ATTRIBUTES
    disable_apn: true
    disable_gcm: true
    config:
      redis:
        url: http://localhost:6379
  textsecure: &TEXTSECURE_ATTRIBUTES
    config:
      cache:
        url: http://localhost:6380
      directory:
        url: http://localhost:6380
  redisio:
    servers:
    - name: pushserver
      port: 6379
    - name: textsecure
      port: 6380

suites:
  - name: default
    # YAML allows us to merge in customizations
    # See: http://stackoverflow.com/questions/9254178/is-there-yaml-syntax-for-sharing-part-of-a-list-or-map
    attributes: *DEFAULT_ATTRIBUTES

  - name: textsecure-source
    # YAML allows us to merge in customizations
    # See: http://stackoverflow.com/questions/9254178/is-there-yaml-syntax-for-sharing-part-of-a-list-or-map
    attributes:
      <<: *DEFAULT_ATTRIBUTES
      textsecure:
        <<: *TEXTSECURE_ATTRIBUTES
        install_method: source

  - name: pushserver-source
    # YAML allows us to merge in customizations
    # See: http://stackoverflow.com/questions/9254178/is-there-yaml-syntax-for-sharing-part-of-a-list-or-map
    attributes:
      <<: *DEFAULT_ATTRIBUTES
      pushserver:
        <<: *PUSHSERVER_ATTRIBUTES
        install_method: source
