name             'textsecure'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures TextSecure server'
long_description 'Installs/Configures TextSecure server'
version          '0.1.0'

depends 'java'
depends 'redis'
depends 'memcached'
depends 'postgresql'
depends 'maven'
